
require 'yaml'
require 'rake/clean'

CONFIG_FILE = "config.yml"

CONFIG = YAML.load(File.open(CONFIG_FILE))
BOOKNAME = CONFIG["bookname"]
PDF_FILE = "#{BOOKNAME}.pdf"
EPUB_FILE = "#{BOOKNAME}.epub"
RE_CHAPS = File.read("CHAPS").split rescue []
RE_PREDEF = File.read("PREDEF").split rescue []
RE_POSTDEF = File.read("POSTDEF").split rescue []
RE_FILES = RE_PREDEF + RE_CHAPS + RE_POSTDEF

CLOBBER.include(PDF_FILE)
CLOBBER.include(EPUB_FILE)
CLEAN.include(BOOKNAME + "-pdf")
CLEAN.include(BOOKNAME + "-epub")

task :default => [PDF_FILE, EPUB_FILE]

file PDF_FILE => RE_FILES do
  sh "review-pdfmaker #{CONFIG_FILE}"
end

file EPUB_FILE => RE_FILES do
  sh "review-epubmaker #{CONFIG_FILE}"
end
